site_name: Coralogix Developer Portal
repo_url: https://github.com/davidmyriel/cx-dave-mkdocs
repo_name: davidmyriel/cx-dave-mkdocs
nav:
  - User Guides:
    - index.md
    - Getting Started:
      - getting-started/index.md
      - getting-started/page1.md
      - getting-started/page2.md
    - Transform Your Data: 
      - newoutput/alert-suppression-rules/index.md
    - Query Your Data: 
      - newoutput/alert-suppression-rules/index.md
    - Monitor Your Data: 
      - newoutput/create-manage-saved-views/index.md
      - newoutput/explore-screen/index.md
    - Monitor Kubernetes Applications: 
      - newoutput/alert-suppression-rules/index.md
    - Synthetic Monitoring: 
      - newoutput/alert-suppression-rules/index.md
    - Application Performance Monitoring: 
      - newoutput/apm/index.md
      - newoutput/apm-onboarding-tutorial/index.md
    - Real User Monitoring: 
      - newoutput/alert-suppression-rules/index.md
    - Alerting: 
      - newoutput/alert-suppression-rules/index.md
      - newoutput/aws-eventbridge-outbound-webhook/index.md
    - Visualizations: 
      - newoutput/alert-suppression-rules/index.md
    - Custom Dashboards: 
      - newoutput/custom-dashboards/index.md
      - newoutput/create-annotations/index.md
      - newoutput/dataprime-widget/index.md
      - newoutput/import-export-custom-dashboards/index.md
    - Security: 
      - newoutput/alert-suppression-rules/index.md
    - Account Administration:
      - newoutput/coralogix-entities/index.md
      - newoutput/groups/index.md
      - Managing Your Organization:
          - newoutput/managing-your-organization/index.md
          - newoutput/managing-your-organization-manage-admins/index.md
          - newoutput/managing-your-organization-my-teams/index.md
          - newoutput/managing-your-organization-organization-settings/index.md
          - newoutput/managing-your-organization-quota-manager/index.md

  - Integrations:
    - integrations/index.md
    - Files:
      - newoutput/cockroachdb/index.md
    - OpenTelemetry: 
      - integrations/open-telemetry/open-telemetry1.md
    - AWS: 
      - newoutput/coralogix-aws-shipper/index.md
      - integrations/aws/aws2.md
    - Azure: 
      - integrations/azure/azure1.md
      - integrations/azure/azure2.md
    - Google Cloud Platform: 
      - newoutput/gcp-getting-started/index.md
      - newoutput/google-alert-center/index.md
      - newoutput/google-workspace-alert-center/index.md
      - newoutput/google-workspace-users/index.md
      - integrations/gcp/gcp2.md
    - Prometheus: 
      - integrations/prometheus/prometheus1.md
    - FluentD:
      - newoutput/alert-suppression-rules/index.md
    - FluentBit:
      - newoutput/alert-suppression-rules/index.md




  - OpenTelemetry:
    - Getting Started: 
      - newoutput/opentelemetry/index.md
      - newoutput/opentelemetry-collector-installation-ecs-fargate/index.md
      - newoutput/opentelemetry-custom-logs/index.md
      - newoutput/opentelemetry-custom-metrics/index.md
      - newoutput/opentelemetry-custom-traces/index.md
      - newoutput/opentelemetry-using-docker/index.md
      - newoutput/running-opentelemetry-as-a-cli-application/index.md
    - Kubernetes Observability:  
      - newoutput/set-up-kubernetes-observability-using-opentelemetry-advanced-configuration/index.md
    - Configuration:  
      - newoutput/alert-suppression-rules/index.md
    - Instrumentation: 
      - newoutput/alert-suppression-rules/index.md
    - Tail Sampling:
      - newoutput/alert-suppression-rules/index.md    

  - Developer Portal:
    - APIs: 
      - reference/index.md
      - newoutput/management-api-endpoints/index.md
      - Data Ingestion API:
        - reference/api/api-rest-singles.md
        - reference/api/api-rest-bulk.md
      - Data Query API: https://heroic-travesseiro-698280.netlify.app/
      - Data Management API: 
        - newoutput/alert-suppression-rules-api/index.md
        - newoutput/incidents-api/index.md
        - newoutput/service-removal-api/index.md
        - newoutput/slo-management-api/index.md
        - newoutput/archive-setup-grpc-api/index.md
        - Alerts API: https://heroic-travesseiro-698280.netlify.app/
    - Coralogix Operator: 
      - newoutput/alert-suppression-rules/index.md
    - Coralogix Terraform Provider:
      - newoutput/alert-suppression-rules/index.md
      - newoutput/terraform-module-for-cloudflare-logpush/index.md
      - newoutput/terraform-modules/index.md
      - newoutput/terraform-modules-aws-s3-logs/index.md
      - newoutput/terraform-modules-for-aws-cloudtrail/index.md
      - newoutput/terraform-modules-for-azure-eventhub/index.md
      - newoutput/terraform-modules-for-gcp-pub-sub/index.md   
      - newoutput/aws-kinesis-data-firehose-terraform-module/index.md
      - newoutput/aws-kinesis-with-lambda-function-terraform-module/index.md
      - newoutput/cloudtrail-s3-terraform/index.md
      - newoutput/terraform-module-for-azure-queue-storage/index.md
      - newoutput/terraform-modules-for-amazon-web-services-aws/index.md
      - newoutput/terraform-modules-for-aws-vpc-flow-logs/index.md
      - newoutput/terraform-modules-for-azure-blob-storage-via-event-grid/index.md
      - newoutput/terraform-modules-for-azure-diagnostic-data/index.md


            
          
      

       

   




plugins:
  - search
  - open-in-new-tab
  - glightbox

theme: 
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
    # - navigation.sections
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
    # - toc.integrate 
  language: en
  markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - attr_list
    - md_in_html
  palette:
    - scheme: slate
      primary: black
      accent: deep blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: default
      primary: green
      accent: deep blue
      toggle: 
        icon: material/weather-sunny
        name: Switch to light mode
